/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Nak4vpky65u
 */
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import { Slider } from "@/components/ui/slider";
import ClickableText from "./clickable-text";

export function SearchPage() {
  return (
    <main className="flex flex-col gap-4 p-4">
      <div className="flex items-center gap-4">
        <Input
          className="flex-1 p-2 border border-gray-200 rounded-md dark:border-gray-800"
          placeholder="Ask a question"
        />
        <Button>Start</Button>
      </div>
      <div className="flex justify-center items-center gap-4 my-4">
        <div className="text-blue-500" />
        <p>Generating search queries...</p>
      </div>
      <div className="flex flex-col gap-2">
        <div className="flex items-center gap-4">
          <Checkbox id="query1" />
          <Label className="flex-1" htmlFor="query1">
            Search query
          </Label>
          <Button size="sm" variant="outline">
            Edit
          </Button>
          <Button className="w-20" size="sm" variant="outline">
            Delete
          </Button>
        </div>
        <div className="flex items-center gap-4">
          <Checkbox id="query2" />
          <Label className="flex-1" htmlFor="query2">
            Search query
          </Label>
          <Button size="sm" variant="outline">
            Edit
          </Button>
          <Button className="w-20" size="sm" variant="outline">
            Delete
          </Button>
        </div>
        <div className="flex items-center gap-4">
          <Checkbox id="query3" />
          <Label className="flex-1" htmlFor="query3">
            Search query
          </Label>
          <Button size="sm" variant="outline">
            Edit
          </Button>
          <Button className="w-20" size="sm" variant="destructive">
            Sure?
          </Button>
        </div>
        <div className="flex items-center gap-4">
          <Checkbox id="query4" />
          <Label className="flex-1" htmlFor="query4">
            Search query
          </Label>
          <Button size="sm" variant="outline">
            Edit
          </Button>
          <Button className="w-20" size="sm" variant="outline">
            Delete
          </Button>
        </div>
        <div className="flex items-center gap-4">
          <Checkbox id="query5" />
          <Input
            className="flex-1 p-2 border border-gray-200 rounded-md dark:border-gray-800"
            placeholder="Search query"
          />
          <Button size="sm" variant="outline">
            Save
          </Button>
        </div>
        <Button className="self-start py-2 px-4" size="sm">
          Add
        </Button>
      </div>
      <h2 className="font-bold">Select search engines</h2>
      <div className="flex flex-col gap-2">
        <div className="flex items-center gap-4">
          <Checkbox id="engine1" />
          <ClickableText className="underline text-sm text-gray-400">
            (only)
          </ClickableText>
          <Label className="flex-1" htmlFor="engine1">
            Search Engine
          </Label>
          <div className="flex items-center gap-4 ml-auto">
            <span>1</span>
            <Slider className="w-32" defaultValue={[3]} max={20} min={1} />
            <span>20</span>
          </div>
          <Input className="w-16" defaultValue={3} type="number" />
        </div>
        <div className="flex items-center gap-4">
          <Checkbox id="engine2" />
          <ClickableText className="underline text-sm text-gray-400">
            (only)
          </ClickableText>
          <Label className="flex-1" htmlFor="engine2">
            Search Engine
          </Label>
          <div className="flex items-center gap-4 ml-auto">
            <span>1</span>
            <Slider className="w-32" defaultValue={[3]} max={20} min={1} />
            <span>20</span>
          </div>
          <Input className="w-16" defaultValue={3} type="number" />
        </div>
        <div className="flex items-center gap-4">
          <Checkbox id="engine3" />
          <ClickableText className="underline text-sm text-gray-400">
            (only)
          </ClickableText>
          <Label className="flex-1" htmlFor="engine3">
            Search Engine
          </Label>
          <div className="flex items-center gap-4 ml-auto">
            <span>1</span>
            <Slider className="w-32" defaultValue={[3]} max={20} min={1} />
            <span>20</span>
          </div>
          <Input className="w-16" defaultValue={3} type="number" />
        </div>
        <div className="flex items-center gap-4">
          <Checkbox id="engine4" />
          <ClickableText className="underline text-sm text-gray-400" to={"#"}>
            (only)
          </ClickableText>
          <Label className="flex-1" htmlFor="engine4">
            Search Engine
          </Label>
          <div className="flex items-center gap-4 ml-auto">
            <span>1</span>
            <Slider className="w-32" defaultValue={[3]} max={20} min={1} />
            <span>20</span>
          </div>
          <Input className="w-16" defaultValue={3} type="number" />
        </div>
      </div>
      <div className="flex items-center gap-4">
        <Button size="sm" variant="outline">
          Select All
        </Button>
        <Button size="sm" variant="outline">
          Select None
        </Button>
        <div className="flex items-center gap-4 ml-auto">
          <span>1</span>
          <Slider className="w-32" defaultValue={[3]} max={20} min={1} />
          <span>20</span>
        </div>
        <Input className="w-16" defaultValue={3} type="number" />
      </div>
      <Button className="my-4">Search</Button>
      <div className="flex justify-center items-center gap-4 my-4">
        <div className="text-blue-500" />
        <p>Searching...</p>
      </div>
    </main>
  );
}
